<?php>
echo " <section id=\"bottom\">\n"; 
echo "        <div class=\"container wow fadeInDown\" data-wow-duration=\"1000ms\" data-wow-delay=\"600ms\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-md-3 col-sm-6\">\n"; 
echo "                    <div class=\"widget\">\n"; 
echo "                        <h3>About Us</h3>\n"; 
echo "                        <ul>\n"; 
echo "                            <li><a href=\"history.html\">History</a></li>\n"; 
echo "                            <li><a href=\"meet-us-leadership.html\">Leadership team</a></li>\n"; 
echo "                            <li><a href=\"meet-us-mentors.html\">Mentors</a></li>\n"; 
echo "                            <li><a href=\"about-us.html#mission\">Team Mission</a></li>\n"; 
echo "                            <li><a href=\"outreach.html\">Outreach</a></li>\n";
echo "                        </ul>\n"; 
echo "                    </div>    \n"; 
echo "                </div><!--/.col-md-3-->\n"; 
echo "\n"; 
echo "                <div class=\"col-md-3 col-sm-6\">\n"; 
echo "                    <div class=\"widget\">\n"; 
echo "                        <h3>Contact Us</h3>\n"; 
echo "                        <ul>\n"; 
echo "                            <li><a href=\"https://www.facebook.com/team670\">Facebook Page: https://www.facebook.com/team670</a></li>\n"; 
echo "                            <li><a href=\"team670@homesteadrobotics.com\">Email: team670@homesteadrobotics.com</a></li>\n"; 
echo "                            <li><a href=\"https://www.youtube.com/user/Team670\">Youtube: https://www.youtube.com/user/Team670</a></li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>    \n"; 
echo "                </div><!--/.col-md-3-->\n"; 
echo "\n"; 
echo "                <div class=\"col-md-3 col-sm-6\">\n"; 
echo "                    <div class=\"widget\">\n"; 
echo "                        <h3>Donations</h3>\n"; 
echo "                        <ul>\n"; 
echo "                            <li><a href=\"sponsor.html\">Sponsor Us</a></li>\n"; 
echo "                            <li><a href=\"sponsor.html#current\">Current Sponsors</a></li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>    \n"; 
echo "                </div><!--/.col-md-3-->\n"; 
echo "\n"; 
echo "                <div class=\"col-md-3 col-sm-6\">\n"; 
echo "                    <div class=\"widget\">\n"; 
echo "                        <h3>Media</h3>\n"; 
echo "                        <ul>\n"; 
echo "                            <li><a href=\"pastcompetition.html\">Videos</a></li>\n"; 
echo "                            <li><a href=\"photos.html\">Photos</a></li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>    \n"; 
echo "                </div><!--/.col-md-3-->\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </section><!--/#bottom-->\n"; 
echo "\n"; 
echo "\n"; 
echo "    <footer id=\"footer\" class=\"midnight-blue\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-sm-6\">\n"; 
echo "                    &copy; 2013 <a target=\"_blank\" href=\"http://shapebootstrap.net/\" title=\"Free Twitter Bootstrap WordPress Themes and HTML templates\">Created from ShapeBootstrap</a>. All Rights Reserved.\n"; 
echo "                    <p>&copy 2015 Website by Homestead Robotics - L.L.</p> <!--By Lily Li, July 2016!-->\n"; 
echo "                </div>\n"; 
echo "\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </footer><!--/#footer-->\n"; 
echo "\n"; 
echo "    <script src=\"js/jquery.js\"></script>\n"; 
echo "    <script src=\"js/bootstrap.min.js\"></script>\n"; 
echo "    <script src=\"js/jquery.prettyPhoto.js\"></script>\n"; 
echo "    <script src=\"js/jquery.isotope.min.js\"></script>\n"; 
echo "    <script src=\"js/main.js\"></script>\n"; 
echo "    <script src=\"js/wow.min.js\"></script>\n"; 
echo "</body>\n";
<?>
